# docker-compose.yaml
version: "3.10"

services:

  frontend:
    image: kchaea/stock-frontend:v1.0
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: front
    tty: true
    ports:
      - 3000:3000

  backend:
    image: kchaea/stock-backend:v1.0
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: back
    tty: true
    ports:
      - 8000:8000