# docker-compose.yaml
version: "3.10"

services:

  frontend:
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: final-front
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/workspace
      - ./assets:/assets
    command: npm start

  backend:
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: final-back
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/workspace
      - ./assets:/assets
    command: uvicorn app.api:app --host 0.0.0.0 --reload