# docker-compose.yaml
version: "3.10"

services:

  frontend:
    image: front:init
    build:
      context: frontend/.
      dockerfile: Dockerfile
    container_name: front-container
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/workspace
      - ./assets:/assets

  backend:
    image: back:init
    build:
      context: backend/.
      dockerfile: Dockerfile
    container_name: back-container
    tty: true
    ports:
      - 8000:8000
    volumes:
      - ./backend:/workspace
      - ./assets:/assets