descriptions = {
        "3LINESTRIKE_Bull": 'Test',
        "3LINESTRIKE_Bear": 'Test',
        "3BLACKCROWS_Bull": 'Test',
        "3BLACKCROWS_Bear": 'Test',
        "EVENINGSTAR_Bull": 'Test',
        "EVENINGSTAR_Bear": 'Test',
        "TASUKIGAP_Bull": 'Test',
        "TASUKIGAP_Bear": 'Test',
        "INVERTEDHAMMER_Bull": 'Test',
        "INVERTEDHAMMER_Bear": 'Test',
        "MATCHINGLOW_Bull": 'Test',
        "MATCHINGLOW_Bear": 'Test',
        "ABANDONEDBABY_Bull": 'Test',
        "ABANDONEDBABY_Bear": 'Test',
        "BREAKAWAY_Bull": 'Test',
        "BREAKAWAY_Bear": 'Test',
        "MORNINGSTAR_Bull": 'Test',
        "MORNINGSTAR_Bear": 'Test',
        "PIERCING_Bull": 'Test',
        "PIERCING_Bear": 'Test',
        "STICKSANDWICH_Bull": 'Test',
        "STICKSANDWICH_Bear": 'Test',
        "THRUSTING_Bull": 'Test',
        "THRUSTING_Bear": 'Test',
        "INNECK_Bull": 'Test',
        "INNECK_Bear": 'Test',
        "3INSIDE_Bull": 'Test',
        "3INSIDE_Bear": 'Test',
        "HOMINGPIGEON_Bull": 'Test',
        "HOMINGPIGEON_Bear": 'Test',
        "DARKCLOUDCOVER_Bull": 'Test',
        "DARKCLOUDCOVER_Bear": 'Test',
        "IDENTICAL3CROWS_Bull": 'Test',
        "IDENTICAL3CROWS_Bear": 'Test',
        "MORNINGDOJISTAR_Bull": 'Test',
        "MORNINGDOJISTAR_Bear": 'Test',
        "XSIDEGAP3METHODS_Bull": 'Test',
        "XSIDEGAP3METHODS_Bear": 'Test',
        "TRISTAR_Bull": 'Test',
        "TRISTAR_Bear": 'Test',
        "GAPSIDESIDEWHITE_Bull": 'Test',
        "GAPSIDESIDEWHITE_Bear": 'Test',
        "EVENINGDOJISTAR_Bull": 'Test',
        "EVENINGDOJISTAR_Bear": 'Test',
        "3WHITESOLDIERS_Bull": 'Test',
        "3WHITESOLDIERS_Bear": 'Test',
        "ONNECK_Bull": 'Test',
        "ONNECK_Bear": 'Test',
        "3OUTSIDE_Bull": 'Test',
        "3OUTSIDE_Bear": 'Test',
        "RICKSHAWMAN_Bull": 'Test',
        "RICKSHAWMAN_Bear": 'Test',
        "SEPARATINGLINES_Bull": 'Test',
        "SEPARATINGLINES_Bear": 'Test',
        "LONGLEGGEDDOJI_Bull": 'Test',
        "LONGLEGGEDDOJI_Bear": 'Test',
        "HARAMI_Bull": 'Test',
        "HARAMI_Bear": 'Test',
        "LADDERBOTTOM_Bull": 'Test',
        "LADDERBOTTOM_Bear": 'Test',
        "CLOSINGMARUBOZU_Bull": 'Test',
        "CLOSINGMARUBOZU_Bear": 'Test',
        "TAKURI_Bull": 'Test',
        "TAKURI_Bear": 'Test',
        "DOJISTAR_Bull": 'Test',
        "DOJISTAR_Bear": 'Test',
        "HARAMICROSS_Bull": 'Test',
        "HARAMICROSS_Bear": 'Test',
        "ADVANCEBLOCK_Bull": 'Test',
        "ADVANCEBLOCK_Bear": 'Test',
        "SHOOTINGSTAR_Bull": 'Test',
        "SHOOTINGSTAR_Bear": 'Test',
        "MARUBOZU_Bull": 'Test',
        "MARUBOZU_Bear": 'Test',
        "UNIQUE3RIVER_Bull": 'Test',
        "UNIQUE3RIVER_Bear": 'Test',
        "2CROWS_Bull": 'Test',
        "2CROWS_Bear": 'Test',
        "BELTHOLD_Bull": 'Test',
        "BELTHOLD_Bear": 'Test',
        "HAMMER_Bull": 'Test',
        "HAMMER_Bear": 'Test',
        "HIGHWAVE_Bull": 'Test',
        "HIGHWAVE_Bear": 'Test',
        "SPINNINGTOP_Bull": 'Test',
        "SPINNINGTOP_Bear": 'Test',
        "UPSIDEGAP2CROWS_Bull": 'Test',
        "UPSIDEGAP2CROWS_Bear": 'Test',
        "GRAVESTONEDOJI_Bull": 'Test',
        "GRAVESTONEDOJI_Bear": 'Test',
        "HIKKAKEMOD_Bull": 'Test',
        "HIKKAKEMOD_Bear": 'Test',
        "HIKKAKE_Bull": 'Test',
        "HIKKAKE_Bear": 'Test',
        "ENGULFING_Bull": 
            """강세 기간 동안, 상승 장악형(Bullish Engulfing)은'\n'
            새로운 저점에서 시가를 나타내고 이전 캔들의 시가 또는'\n'
            시가 위에서 마감합니다. 이는 하락세가 모멘텀을 잃었고'\n'
            강세가 힘을 얻고있음을 나타냅니다. 패턴의 효과를 증가시키는'\n'
            요소는 다음과 같습니다.'\n'
            1) 첫 번째 캔들은 몸통이 작고 두 번째 캔들은 몸통이 큽니다.'\n'
            2) 길거나 매우 빠르게 움직인 후 패턴이 나타납니다.'\n'
            3) 두 번째 캔들 몸통에는 많은 거래량이 있습니다.'\n'
            'Test') 두 번째 캔들은 1개 이상의 몸통을 장악합니다.""",

        "ENGULFING_Bear": 
            """상승 추세 중에 발생하는 이 패턴은 큰 음봉 몸통이 특징이며,'\n'
            양봉을 장악합니다.(그림자를 장악할 필요는 없습니다).'\n'
            이는 상승세가 타격을 입었고 하락세가 힘을 얻고 있음을 나타냅니다.'\n'
            장악형(engulfing)은 쓰리 아웃사이드(Three Outside)패턴의 처음 두 캔들이며'\n'
            이는 주요 반전 신호입니다. 이 신호의 신뢰성을 높이는 요소 :'\n'
            1) 첫 번째 캔들은 몸통이 매우 작고 두 번째 캔들은 몸통이 매우 큽니다.'\n'
            2) 패턴이 오래 걸리거나 매우 빠르게 움직 인 후에 나타납니다.'\n'
            3) 두 번째 음봉에 많은 거래량이 나타납니다.'\n'
            'Test') 두 번째 캔들은 하나 이상의 몸통을 장악합니다.""",

        "MATHOLD_Bull": 'Test',
        "MATHOLD_Bear": 'Test',
        "HANGINGMAN_Bull": 'Test',
        "HANGINGMAN_Bear": 'Test',
        "RISEFALL3METHODS_Bull": 'Test',
        "RISEFALL3METHODS_Bear": 'Test',
        "KICKING_Bull": 'Test',
        "KICKING_Bear": 'Test',
        "DRAGONFLYDOJI_Bull": 'Test',
        "DRAGONFLYDOJI_Bear": 'Test',
        "CONCEALBABYSWALL_Bull": 'Test',
        "CONCEALBABYSWALL_Bear": 'Test',
        "3STARSINSOUTH_Bull": 'Test',
        "3STARSINSOUTH_Bear": 'Test',
        "DOJI_Bull": 'Test',
        "DOJI_Bear": '표시하락세 반전신뢰도중간설명강세 기간에 시장은 장대 양봉에 힘을 실어주고 두 번째 캔들에 갭(Gap)을 만듭니다. 그러나 두 번째 캔들은 작은 범위 내에서 거래되며 시가 또는 시가와 근접하여 마감합니다. 이 시나리오는 일반적으로 현재 추세에 대한 신뢰의 침식을 보여줍니다. 추세 반전의 확인은 다음 캔들의 더 낮은 시가일 것입니다.'
}